// App RBAC seed + GoTrue claims-hook wiring (K2). When an auth resource is created with
// `auth.rbac: true`, Drop provides the Supabase-pattern authorization schema in the APP's OWN bound
// Postgres database — three many-to-many tables (users↔roles↔permissions, both hops) plus a Postgres
// function GoTrue's **custom access token hook** calls on every issued JWT to stamp resolved
// `roles: []` / `permissions: []` arrays into the token claims. The app then reads those claims
// (server-side via `@drop/auth`'s `verifyRequest`, or in Postgres RLS — a documented pattern).
//
// SEED-APPLICATION MODEL (v1, an honest deviation — see docs/auth.html "Roles & permissions"):
//   The plan called for shipping these as "engine-provision assets". The API has no SQL-execution
//   path against a tenant DB yet (the I4 SQL console is a later slice) and the bound database may
//   PRE-EXIST the auth resource, so Drop cannot silently run this DDL at create time. Therefore the
//   seed ships as (a) exported SQL assets (this module), (b) a `drop auth rbac-seed <name>` CLI
//   command that PRINTS the SQL for one-time psql application by the operator, and (c) the
//   GOTRUE_HOOK_* env is plumbed onto the engine whenever `rbac: true` so the hook activates the
//   moment the function exists. All DDL is idempotent (IF NOT EXISTS / CREATE OR REPLACE), so
//   re-running the seed is safe.
//
// GoTrue COMPATIBILITY (verified): the pinned engine `supabase/gotrue:v2.170.0` (2025-03-06) supports
// the pg-functions custom access token hook — the hook infrastructure is present by v2.145.0
// (2024-03-26). The hook is configured with two env vars:
//   GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED=true
//   GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI=pg-functions://postgres/public/drop_access_token_hook
// GoTrue's URI parser (validatePostgresPath) uses ONLY the schema + function name from the path; the
// host/db segment ("postgres") is ignored — so this URI is correct even though our bound database is
// named `app`. GoTrue calls the function over its EXISTING connection (as the `app` role, which owns
// the seeded tables + function), so no cross-role GRANTs are required — simpler than Supabase's
// multi-role setup where the hook is granted to `supabase_auth_admin`.

/** The Postgres schema + function name GoTrue's custom-access-token hook calls. */
export const RBAC_HOOK_SCHEMA = "public";
export const RBAC_HOOK_FUNCTION = "drop_access_token_hook";

/** The pg-functions hook URI. The leading `postgres` segment is a GoTrue convention and is IGNORED by
 *  its parser (only schema + function are used) — correct even though the bound DB is `app`. */
export const RBAC_HOOK_URI = `pg-functions://postgres/${RBAC_HOOK_SCHEMA}/${RBAC_HOOK_FUNCTION}`;

/** GoTrue env var names for the custom access token hook (v2.145.0+; the pinned v2.170.0 supports it). */
export const RBAC_HOOK_ENABLED_ENV = "GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_ENABLED";
export const RBAC_HOOK_URI_ENV = "GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_URI";

/** The three seeded table names (Supabase pattern; app-defined vocabulary, disjoint from platform `can()`). */
export const RBAC_TABLES = {
  roles: "app_roles",
  rolePermissions: "app_role_permissions",
  userRoles: "app_user_roles",
} as const;

/** The many-to-many RBAC schema (both hops: users↔roles, roles↔permissions). Idempotent DDL. */
export const RBAC_TABLES_SQL = `-- App RBAC tables (K2) — the vocabulary is entirely app-defined and disjoint from Drop's platform roles.
-- users ↔ roles ↔ permissions, both hops many-to-many. Owned by the \`app\` role (the connection GoTrue uses).
CREATE TABLE IF NOT EXISTS ${RBAC_TABLES.roles} (
  id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text   NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ${RBAC_TABLES.rolePermissions} (
  role_id    bigint NOT NULL REFERENCES ${RBAC_TABLES.roles} (id) ON DELETE CASCADE,
  permission text   NOT NULL,
  PRIMARY KEY (role_id, permission)
);

-- user_id is GoTrue's auth.users.id (a uuid). Deliberately NOT a hard FK to auth.users, so this seed
-- can be applied independently of the engine's own migration ordering.
CREATE TABLE IF NOT EXISTS ${RBAC_TABLES.userRoles} (
  user_id uuid   NOT NULL,
  role_id bigint NOT NULL REFERENCES ${RBAC_TABLES.roles} (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS ${RBAC_TABLES.userRoles}_user_id_idx ON ${RBAC_TABLES.userRoles} (user_id);`;

/** The claims-hook Postgres function GoTrue calls per issued JWT. It resolves the user's roles +
 *  permissions by joining the two tables on `event->>'user_id'` and stamps them as `roles`/`permissions`
 *  arrays into the token `claims`, returning the modified event (the GoTrue custom-access-token
 *  contract). CREATE OR REPLACE → idempotent. SECURITY DEFINER + a fixed search_path mirror Supabase's
 *  documented hook posture; here definer == invoker == the owning `app` role, so no extra GRANTs. */
export const RBAC_HOOK_FUNCTION_SQL = `-- GoTrue custom-access-token hook (K2): stamp resolved roles + permissions into every JWT's claims.
CREATE OR REPLACE FUNCTION ${RBAC_HOOK_SCHEMA}.${RBAC_HOOK_FUNCTION}(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ${RBAC_HOOK_SCHEMA}, pg_temp
AS $$
DECLARE
  uid    uuid;
  claims jsonb;
  roles  text[];
  perms  text[];
BEGIN
  claims := coalesce(event -> 'claims', '{}'::jsonb);
  -- A malformed / absent user_id must not fail token issuance — fall back to no roles.
  BEGIN
    uid := (event ->> 'user_id')::uuid;
  EXCEPTION WHEN others THEN
    uid := NULL;
  END;

  SELECT coalesce(array_agg(DISTINCT r.name), ARRAY[]::text[])
    INTO roles
    FROM ${RBAC_TABLES.userRoles} ur
    JOIN ${RBAC_TABLES.roles} r ON r.id = ur.role_id
   WHERE ur.user_id = uid;

  SELECT coalesce(array_agg(DISTINCT rp.permission), ARRAY[]::text[])
    INTO perms
    FROM ${RBAC_TABLES.userRoles} ur
    JOIN ${RBAC_TABLES.rolePermissions} rp ON rp.role_id = ur.role_id
   WHERE ur.user_id = uid;

  claims := jsonb_set(claims, '{roles}', to_jsonb(roles));
  claims := jsonb_set(claims, '{permissions}', to_jsonb(perms));

  RETURN jsonb_set(event, '{claims}', claims);
END;
$$;`;

/** The env vars that activate the hook on the engine (emitted by the GoTrue adapter when rbac is on). */
export function rbacHookEnv(): Record<string, string> {
  return { [RBAC_HOOK_ENABLED_ENV]: "true", [RBAC_HOOK_URI_ENV]: RBAC_HOOK_URI };
}

/** The full seed SQL (tables + hook function), with a header describing how/where to apply it. `name`
 *  (the auth resource) is used only in the comment header — the DDL itself is resource-independent. */
export function rbacSeedSql(name = "<auth>"): string {
  return `-- Drop app-RBAC seed for auth resource "${name}" (K2).
-- Apply ONCE against the auth resource's BOUND database (the \`app\` database) as the \`app\` role. Open an
-- authenticated tunnel with \`drop db proxy <db>\` (prints a local port), then:
--     drop auth rbac-seed ${name} | psql "postgres://app@127.0.0.1:<port>/app"
-- All statements are idempotent (IF NOT EXISTS / CREATE OR REPLACE), so re-running is safe.
-- The GoTrue custom-access-token hook is already wired (GOTRUE_HOOK_CUSTOM_ACCESS_TOKEN_*) whenever the
-- resource was created with \`auth.rbac: true\`; it activates the moment this function exists.

${RBAC_TABLES_SQL}

${RBAC_HOOK_FUNCTION_SQL}
`;
}
