// GENERATED by scripts/gen-client.mjs from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate with `npm run gen:client` (or `node build.mjs`). The spec version is "2.0.0".
// A typed method per registered route + its response type. The runtime wrapper (createClient) is the
// hand-written ./index.ts; this file is pure types + a thin factory, zero runtime dependencies.

/** Accepted request-body payloads: a JSON string for JSON routes, or bytes for a binary upload. Defined
 *  locally so the package needs no DOM lib (bun-types provides fetch but not BodyInit under lib:ESNext). */
export type RequestBody = string | Uint8Array | ArrayBuffer | ArrayBufferView;

export interface RequestOptions {
  query?: Record<string, string | undefined>;
  body?: RequestBody;
  contentType?: string;
}

/** The low-level request function createClient supplies to the generated methods. */
export type RequestFn = (method: string, path: string, opts?: RequestOptions) => Promise<unknown>;

export type GetVersionResponse = { version: string };
export type GetMeResponse = { email: string; admin: boolean; unresolvedEvents: number };
export type GetFeaturesResponse = { llmEnabled: boolean };
export type ListOrgsResponse = { orgs: ({ slug: string; name: string; kind: "personal" | "team"; role: "owner" | "admin" | "member" | "viewer" })[] };
export type GetOrgResponse = { slug: string; name: string; kind: "personal" | "team"; members: ({ email: string; role: "owner" | "admin" | "member" | "viewer" })[] };
export type GetOrgUsageResponse = { org: { slug: string; name: string; kind: "personal" | "team" }; workloads: { site: number; app: number; database: number; bucket: number; cache: number; auth: number; total: number }; cap: number; quota: { hard: Record<string, string>; used: Record<string, string> } | null; storage: { databases: { count: number; requestedBytes: number }; buckets: { count: number; bytes: number }; caches: { count: number; bytes: number }; budget: number | null } };
export type ListSitesResponse = { sites: ({ name: string; type: "site" | "app" | "database" | "bucket" | "cache" | "auth"; owner: string; visibility: "public" | "private" | "password"; url: string; current: string | null; org: { slug: string; name: string; kind: "personal" | "team" } | null; capabilities: ("read" | "logs" | "publish" | "deploy" | "db:create" | "connect" | "exec" | "query" | "rollback" | "configure" | "expose" | "share" | "transfer" | "delete" | "config.read")[] })[] };
export type GetSiteResponse = { name: string; type: "site" | "app" | "database" | "bucket" | "cache" | "auth"; owner: string; org: { slug: string; name: string; kind: "personal" | "team" } | null; collaborators: string[]; members: ({ email: string; role: "owner" | "editor" | "viewer" })[]; visibility: "public" | "private" | "password"; current: string | null; url: string; versions: { id: string; publishedBy: string; createdAt: string; fileCount: number; bytes: number; config?: Record<string, unknown> }[]; capabilities: ("read" | "logs" | "publish" | "deploy" | "db:create" | "connect" | "exec" | "query" | "rollback" | "configure" | "expose" | "share" | "transfer" | "delete" | "config.read")[]; status: { status: "running" | "asleep" | "progressing" | "degraded" | "stopped" | "error"; reason: string }; app?: Record<string, unknown>; database?: Record<string, unknown>; cache?: Record<string, unknown>; auth?: Record<string, unknown>; bucket?: Record<string, unknown>; tcp?: Record<string, unknown>; previews?: { label: string; versionId: string; url: string; createdBy: string; createdAt: string; expiresAt: string; kind: string; hasDb: boolean; branchedFrom?: string; branchedAt?: string }[]; uptime?: { last24hPct: number | null; lastCheck: { ok: boolean; latencyMs: number; status: number; at: string } | null } };
export type PublishSiteVersionResponse = { url: string; version: string; files: number; bytes: number; preview?: { label: string; url: string; versionId: string; expiresAt: string } };

/** Build the typed method map over a low-level `request` (see createClient in ./index.ts). */
export function createMethods(request: RequestFn) {
  return {
  getVersion: (): Promise<GetVersionResponse> =>
    request("GET", `/version`) as Promise<GetVersionResponse>,
  getMe: (): Promise<GetMeResponse> =>
    request("GET", `/v1/me`) as Promise<GetMeResponse>,
  getFeatures: (): Promise<GetFeaturesResponse> =>
    request("GET", `/v1/features`) as Promise<GetFeaturesResponse>,
  listOrgs: (): Promise<ListOrgsResponse> =>
    request("GET", `/v1/orgs`) as Promise<ListOrgsResponse>,
  getOrg: (params: { slug: string }): Promise<GetOrgResponse> =>
    request("GET", `/v1/orgs/${encodeURIComponent(params.slug)}`) as Promise<GetOrgResponse>,
  getOrgUsage: (params: { slug: string }): Promise<GetOrgUsageResponse> =>
    request("GET", `/v1/orgs/${encodeURIComponent(params.slug)}/usage`) as Promise<GetOrgUsageResponse>,
  listSites: (query?: { org?: string }): Promise<ListSitesResponse> =>
    request("GET", `/v1/sites`, { query }) as Promise<ListSitesResponse>,
  getSite: (params: { name: string }): Promise<GetSiteResponse> =>
    request("GET", `/v1/sites/${encodeURIComponent(params.name)}`) as Promise<GetSiteResponse>,
  publishSiteVersion: (params: { name: string }, body: RequestBody, query?: { org?: string; preview?: string; expire_days?: string }): Promise<PublishSiteVersionResponse> =>
    request("POST", `/v1/sites/${encodeURIComponent(params.name)}/versions`, { body, contentType: "application/gzip", query }) as Promise<PublishSiteVersionResponse>,
  };
}

/** The typed client surface returned by createClient. */
export type DropMethods = ReturnType<typeof createMethods>;
