apiVersion: v1
kind: Service
metadata:
  name: {{ include "drop.fullname" . }}-edge
  labels:
    {{- include "drop.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "drop.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: edge
