{{- if and (not .Values.secret.existingSecret) .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drop.fullname" . }}-secrets
  labels:
    {{- include "drop.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.googleClientSecretKey }}: {{ required "secret.googleClientSecret is required when secret.create=true" .Values.secret.googleClientSecret | quote }}
  {{ .Values.secret.sessionSecretKey }}: {{ required "secret.sessionSecret is required when secret.create=true" .Values.secret.sessionSecret | quote }}
{{- end -}}
