// L5 — generate the typed @drop/client method map + response types from docs/openapi.json.
//
//   node scripts/gen-client.mjs
//
// Emits packages/client/src/generated.ts (committed, deterministic): one response-type per registered
// route + a `createMethods(request)` factory of typed methods. The stable runtime wrapper lives in the
// hand-written packages/client/src/index.ts (createClient / error handling). ZERO runtime deps.

import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

const root = new URL("..", import.meta.url);
const specPath = new URL("./docs/openapi.json", root);
const outPath = new URL("./packages/client/src/generated.ts", root);

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/** JSON Schema → a TypeScript type expression. */
function tsType(schema) {
  if (!schema || typeof schema !== "object" || Object.keys(schema).length === 0) return "unknown";
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.anyOf) return schema.anyOf.map(tsType).join(" | ");
  const t = schema.type;
  if (Array.isArray(t)) return t.map((x) => (x === "null" ? "null" : primType(x))).join(" | ");
  if (t === "array") {
    const inner = tsType(schema.items);
    return /[|&]/.test(inner) ? `(${inner})[]` : `${inner}[]`;
  }
  if (t === "object") {
    if (schema.additionalProperties && schema.additionalProperties !== true) {
      return `Record<string, ${tsType(schema.additionalProperties)}>`;
    }
    if (schema.properties) return objectType(schema);
    return "Record<string, unknown>";
  }
  return primType(t);
}

function primType(t) {
  if (t === "integer" || t === "number") return "number";
  if (t === "boolean") return "boolean";
  if (t === "null") return "null";
  return "string";
}

function objectType(schema) {
  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties).map(([k, v]) => {
    const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
    return `${key}${required.has(k) ? "" : "?"}: ${tsType(v)}`;
  });
  return `{ ${fields.join("; ")} }`;
}

function main() {
  const spec = JSON.parse(readFileSync(specPath, "utf8"));
  const responseTypes = [];
  const methods = [];

  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) {
      const name = op.operationId;
      const Resp = `${pascal(name)}Response`;
      const resSchema = op.responses?.["200"]?.content?.["application/json"]?.schema;
      responseTypes.push(`export type ${Resp} = ${tsType(resSchema)};`);

      const params = (op.parameters ?? []).filter((p) => p.in === "path");
      const queries = (op.parameters ?? []).filter((p) => p.in === "query");
      const body = op.requestBody;

      const args = [];
      if (params.length) args.push(`params: { ${params.map((p) => `${p.name}: string`).join("; ")} }`);
      if (body) {
        const isBinary = Object.values(body.content)[0]?.schema?.format === "binary";
        const bodyType = isBinary ? "RequestBody" : tsType(Object.values(body.content)[0]?.schema);
        args.push(`body: ${bodyType}`);
      }
      if (queries.length) {
        const qType = queries.map((q) => `${q.name}?: string`).join("; ");
        args.push(`query?: { ${qType} }`);
      }

      // build the runtime path template, substituting {param} → ${encodeURIComponent(params.param)}
      const template = path.replace(/\{([^}]+)\}/g, (_, p) => "${encodeURIComponent(params." + p + ")}");
      const opts = [];
      if (body) {
        const ct = Object.keys(body.content)[0];
        opts.push("body");
        opts.push(`contentType: ${JSON.stringify(ct)}`);
      }
      if (queries.length) opts.push("query");
      const optsArg = opts.length ? `, { ${opts.join(", ")} }` : "";

      methods.push(
        `  ${name}: (${args.join(", ")}): Promise<${Resp}> =>\n` +
          `    request(${JSON.stringify(method.toUpperCase())}, \`${template}\`${optsArg}) as Promise<${Resp}>,`,
      );
    }
  }

  const out = `// GENERATED by scripts/gen-client.mjs from docs/openapi.json — DO NOT EDIT BY HAND.
// Regenerate with \`npm run gen:client\` (or \`node build.mjs\`). The spec version is ${JSON.stringify(spec.info.version)}.
// A typed method per registered route + its response type. The runtime wrapper (createClient) is the
// hand-written ./index.ts; this file is pure types + a thin factory, zero runtime dependencies.

/** Accepted request-body payloads: a JSON string for JSON routes, or bytes for a binary upload. Defined
 *  locally so the package needs no DOM lib (bun-types provides fetch but not BodyInit under lib:ESNext). */
export type RequestBody = string | Uint8Array | ArrayBuffer | ArrayBufferView;

export interface RequestOptions {
  query?: Record<string, string | undefined>;
  body?: RequestBody;
  contentType?: string;
}

/** The low-level request function createClient supplies to the generated methods. */
export type RequestFn = (method: string, path: string, opts?: RequestOptions) => Promise<unknown>;

${responseTypes.join("\n")}

/** Build the typed method map over a low-level \`request\` (see createClient in ./index.ts). */
export function createMethods(request: RequestFn) {
  return {
${methods.join("\n")}
  };
}

/** The typed client surface returned by createClient. */
export type DropMethods = ReturnType<typeof createMethods>;
`;

  writeFileSync(outPath, out);
  console.log(`✓ wrote packages/client/src/generated.ts (${methods.length} methods)`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
