// Wires the generated route tree into a TanStack Router instance. TanStack Start calls
// `createRouter` to build both the SSR and client routers. `routeTree.gen.ts` is generated by
// the tanstackStart() vite plugin from the files in src/routes — it's created on `vite dev` /
// `vite build`, so it does not exist until the first build.
import { createRouter } from '@tanstack/react-router'
import { routeTree } from './routeTree.gen'

// TanStack Start's server + client entries import `getRouter` from this module (resolved as the
// "router entry") to build a fresh router per request / for hydration.
export function getRouter() {
  return createRouter({
    routeTree,
    defaultPreload: 'intent',
    scrollRestoration: true,
  })
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
